"""create call_sessions table

Revision ID: 67c73ad0663b
Revises: 
Create Date: 2026-02-24 10:49:40.147481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c73ad0663b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caller_phone', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('ai_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'on_hold', 'transferring', 'completed', 'failed', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_business_id'), 'call_sessions', ['business_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_caller_phone'), 'call_sessions', ['caller_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_sessions_caller_phone'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_business_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
