"""add duration_seconds column to call_sessions

Revision ID: 85bc5d8da70b
Revises: 67c73ad0663b
Create Date: 2026-02-24 15:22:40.279963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bc5d8da70b'
down_revision: Union[str, Sequence[str], None] = '67c73ad0663b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_sessions', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_sessions', 'duration_seconds')
    # ### end Alembic commands ###
